create extension if not exists "pgcrypto";

create table if not exists countries (
  id bigint generated by default as identity primary key,
  public_id uuid default gen_random_uuid() unique not null,
  name text not null,
  code text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists climbing_areas (
  id bigint generated by default as identity primary key,
  public_id uuid default gen_random_uuid() unique not null,
  country_id bigint references countries(id) on delete set null,
  name varchar(100) not null,
  description text,
  image_path text,
  latitude numeric,
  longitude numeric,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists climbing_zones (
  id bigint generated by default as identity primary key,
  public_id uuid default gen_random_uuid() unique not null,
  area_id bigint references climbing_areas(id) on delete cascade,
  name text not null,
  image_path text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists climbing_routes (
  id bigint generated by default as identity primary key,
  public_id uuid default gen_random_uuid() unique not null,
  zone_id bigint references climbing_zones(id) on delete cascade,
  name text not null,
  type text not null,
  grade text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists climbing_ascents (
  id bigint generated by default as identity primary key,
  public_id uuid default gen_random_uuid() unique not null,
  route_id bigint references climbing_routes(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  type text not null,
  date date not null,
  rating smallint check (rating >= 1 and rating <= 5),
  grade text not null,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table countries enable row level security;
alter table climbing_areas enable row level security;
alter table climbing_zones enable row level security;
alter table climbing_routes enable row level security;
alter table climbing_ascents enable row level security;

create policy "countries are public"
on countries for select
using (true);

create policy "areas are public"
on climbing_areas for select
using (true);

create policy "zones are public"
on climbing_zones for select
using (true);

create policy "routes are public"
on climbing_routes for select
using (true);

create policy "users can read own ascents"
on climbing_ascents for select
using (auth.uid() = user_id);

create policy "users can insert own ascents"
on climbing_ascents for insert
with check (auth.uid() = user_id);

create policy "users can update own ascents"
on climbing_ascents for update
using (auth.uid() = user_id);

create policy "users can delete own ascents"
on climbing_ascents for delete
using (auth.uid() = user_id);
